name: hello-workflow

on:
  workflow_dispatch:
    inputs: 
      caller_message:
        description: 'A message from the caller'
        required: true

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        shell: bash
        run: |
          echo "The caller says: ${{ github.event.inputs.caller_message }}"
    outputs:
      response_message: "this was returned from GitHub actions"
